<a href="https://colab.research.google.com/github/shakin-shahria/Python_programming/blob/main/CSE_3812/AI_lab_class03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [ ]:
class My_color:
      white = "RED+BLUE+Green"
c1 = My_color()
print(c1.white)

RED+BLUE+Green


In [ ]:
## Class,Obj,Function
class Bat:
  def __init__(self,size,color):
        self.size= size
        self.color= color
c1 = Bat("55","red")
print("Bat size:",c1.size)
print("Bat color ",c1.color)


Bat size: 55
Bat color  red


In [ ]:
## Inheritence
class papa:
  def __init__(self,eyes,height):
      self.eyes = eyes
      self.height = height
c1 = papa("red", "1127cm")
#print(c1.eyes)

class son (papa):
  def __init__(self, eyes, height):
      super().__init__(eyes, height)

c2 = son ("pale red", "1231cm")
print (c2.eyes)

pale red


In [5]:
## NumPy
import numpy as np
Array = np.array([1,2,3,4,56])
print(Array)

[ 1  2  3  4 56]


In [10]:
## 2-d array

import numpy
Array = numpy.array([[2,3,4],[2,3,4]])
print(Array)


[[2 3 4]
 [2 3 4]]


In [11]:
# check the number of dimensions

import numpy
a= numpy.array(7)
b= numpy.array([[343,34534,78,],[3424,45,5675]])
c= numpy.array([[4,5,6],[44,21,45],[46,14,77]])
print(a.ndim)
print(b.ndim)
print(c.ndim)

0
2
2


In [18]:
#higher dimension of arrays

import numpy as np
a = np.array([2,4,5,6,7,8], ndmin=7)
print(a)
print("number of dimensions:", a.ndim)

[[[[[[[2 4 5 6 7 8]]]]]]]
number of dimensions: 7


In [27]:
## array indexing

import numpy
Array = numpy.array([[2,3,4],[77,55,99],[1111,333333,6666666]])
#print(Array)
print(Array[0]+ Array[2])


[   1113  333336 6666670]


In [7]:
import numpy as np
a = np.array ([[2,3,4,],[33,44,6,],[222,7777,888]])
print('This is the 3rd element of 2nd roe: ', a[1,2]) # inside the a[1,2] 1 indicates the row/array and 2 indicates the colum/element

This is the 3rd element of 2nd roe:  6


In [12]:
# Array slicing

import numpy as np

a = np.array([1,2,3,4,5,6,7,33,555,777,8888])

print(a[4:])
print(a[:6])
print(a[2:5])
print(a[-3:-1])



[   5    6    7   33  555  777 8888]
[1 2 3 4 5 6]
[3 4 5]
[555 777]


In [13]:
#Step

import numpy as np

a = np.array([2,434,565,87878,989,433322,4343])
print(a[1:-1:2])


[   434  87878 433322]


In [16]:
#slicing 2d array


import numpy as np
a = np.array ([[1,2,3],[11,22,33]])
print(a[0,1:])

[2 3]


In [17]:
import numpy as np

a = np.array([[1,2,3],[22,33,44]])
print(a[0:2,1:4]) # firsr part indicates row 0 to 2 and the second part indicates colum 1 to 4


[[ 2  3]
 [33 44]]


In [4]:
#array reshaping
import numpy as np
a = np.array([1,2,3,44,666,777,888,999])
print(a)
new_a = a.reshape(2,2,-1)
print("new array is: ",new_a)
# the reshaping operation transforms the 1-dimensional array a into a 3-dimensional array 'new_a' with dimensions (2, 2, n),
# where n depends on the number of elements in 'a'

[  1   2   3  44 666 777 888 999]
new array is:  [[[  1   2]
  [  3  44]]

 [[666 777]
  [888 999]]]


In [7]:
#pandas

import pandas as pd
mydataset = {

             'cars' : ["BMW", "VOLVO"],
             'passing' : ["45","232"]

}
print(mydataset)
myvar = pd.DataFrame (mydataset)
print(myvar)


{'cars': ['BMW', 'VOLVO'], 'passing': ['45', '232']}
    cars passing
0    BMW      45
1  VOLVO     232


In [ ]:
# pandas_taking input from file
import pandas as pd
df = pd. read_csv("data.csv")
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   